### ISSUE TITLE
Help me out on this error

### ISSUE THREAD

**Issue by infawikirich** [techwithtim/Flask-Web-App-Tutorial#11]
C:\Users\CBAS\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_sqlalchemy\__init__.py:834: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "C:/Users/CBAS/Documents/Python Scripts/Pycharm/Tech with Tim/main.py", line 9, in <module> app = create_app()
  File "C:\Users\CBAS\Documents\Python Scripts\Pycharm\Tech with Tim\website\__init__.py", line 27, in create_app create_database(app)
  File "C:\Users\CBAS\Documents\Python Scripts\Pycharm\Tech with Tim\website\__init__.py", line 38, in create_database
    db.create_all(app=app)
  File "C:\Users\CBAS\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 1039, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "C:\Users\CBAS\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 1031, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "C:\Users\CBAS\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 962, in get_engine
    return connector.get_engine()
  File "C:\Users\CBAS\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 555, in get_engine
    options = self.get_options(sa_url, echo)
  File "C:\Users\CBAS\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 570, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "C:\Users\CBAS\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_sqlalchemy\__init__.py", line 914, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute

**Comment by rustedorc** [comment]
^^^ i have this exact same issue its something to do with the 'db.create_all(app=app)' but im not sure what

**Comment by pvrvishal** [comment]
SQLALCHEMY_TRACK_MODIFICATIONS = False

> Add this in your __init__.py file to resolve this warning

**Comment by Abdoulshehu** [comment]
Check_password_hash is not working
