### ISSUE TITLE
Could Not Import 'App'

### ISSUE THREAD

**Issue by DEMeyers** [techwithtim/Flask-Web-App-Tutorial#110]
I read the 53 current issues.  I did make the change in the __init__.py for the function def create_database(app):
I still get the above error.  I am using Visual Studio.

Here is my test messages.  

This run is with debug.

'c:\Users\Dan\.vscode\extensions\ms-python.python-2023.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '53234' '--' '-m' 'flas 'run' '--no-debugger' '--no-reload' 
Usage: python -m flask run [OPTIONS]
Try 'python -m flask run --help' for help.

Error: Could not import 'app'.

This run is without debug

\website\models.py:11: SAWarning: Can't validate argument 'primary_Key'; can't locate any SQLAlchemy dialect named 'primary'
  id = db.Column(db.Integer, primary_Key=True)
Traceback (most recent call last):
  File "c:\Users\Dan\Desktop\FLASK WEB APP TUTORIAL\main.py", line 11, in <module>      
    app = create_app()
  File "c:\Users\Dan\Desktop\FLASK WEB APP TUTORIAL\website\__init__.py", line 20, in create_app
    from .views import views
  File "c:\Users\Dan\Desktop\FLASK WEB APP TUTORIAL\website\views.py", line 3, in <module>
    from .models import Note
  File "c:\Users\Dan\Desktop\FLASK WEB APP TUTORIAL\website\models.py", line 10, in <module>
    class Note(db.Model):
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_sqlalchemy\model.py", line 100, in __init__
    super().__init__(name, bases, d, **kwargs)
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_sqlalchemy\model.py", line 120, in __init__
    super().__init__(name, bases, d, **kwargs)
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\decl_api.py", line 199, in __init__
    _as_declarative(reg, cls, dict_)
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\decl_base.py", line 578, in __init__
    self._early_mapping(mapper_kw)
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\decl_base.py", line 370, in _early_mapping
    self.map(mapper_kw)
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1791, in map
    mapper_cls(self.cls, self.local_table, **self.mapper_args),
  File "<string>", line 2, in __init__
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\mapper.py", line 859, in __init__
    self._configure_pks()
  File "C:\Users\Dan\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\mapper.py", line 1601, in _configure_pks
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Mapper Mapper[Note(note)] could not assemble any primary key columns for mapped table 'note'

**Comment by DEMeyers** [comment]
Closing issue.
