### ISSUE TITLE
Database not being created.

### ISSUE THREAD

**Issue by ScalvyC** [techwithtim/Flask-Web-App-Tutorial#158]
Code:
"from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path

db = SQLAlchemy()
DB_NAME = "CSIA.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'www'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import Admin, Employees, Product, Order, OrderItem, InventoryPage, Supplier
    
    create_database(app)
    with app.app_context():
        db.create_all()

    return app

def create_database(app):
    if not path.exists('Website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')
"

Error:
"S D:\MY PC\Documents\> & "C:/Program Files/Python312/python.exe" "d:/MY PC/Documents/main.py"
Traceback (most recent call last):
  File "d:\MY PC\Documents\main.py", line 3, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "d:\MY PC\Documents\Website\__init__.py", line 22, in create_app
    create_database(app)
  File "d:\MY PC\Documents\Website\__init__.py", line 30, in create_database
    db.create_all(app=app)
TypeError: SQLAlchemy.create_all() got an unexpected keyword argument 'app'"

**Comment by RasheshDesai** [comment]
Hi @ScalvyC, 

The create_all() method does not accept an app keyword argument. Instead, you must ensure the Flask application context is active before calling create_all().

Update your create_database() function like this:

**def create_database(app):
    if not path.exists('Website/' + DB_NAME):
        with app.app_context():
            db.create_all()
        print('Created Database!')**

Also, I found a small issue in your create_app() function:
Replace: 
**app = Flask(name) to app = Flask(__name__)**

Let me know if it still doesn't work.
