### ISSUE TITLE
I get an sqlalchemy operational error

### ISSUE THREAD

**Issue by irllyneedhelp** [techwithtim/Flask-Web-App-Tutorial#19]
I was following through the youtube guide and ran into an sqlalchemy operational error: no such column: user password

I tried copying the exact code from the github and i still got the error.

Here is the error:

sqlalchemy.exc.OperationalError
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.password
[SQL: SELECT user.id AS user_id, user.email AS user_email, user.password AS user_password, user.first_name AS user_first_name 
FROM user 
WHERE user.email = ?
 LIMIT ? OFFSET ?]
[parameters: ('creamyclydee@gmail.com', 1, 0)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

Traceback (most recent call last)
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
self.dialect.do_execute(
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
cursor.execute(statement, parameters)
The above exception was the direct cause of the following exception:
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 2088, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 2070, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\flask\app.py", line 1499, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "C:\Codes\Project\website\auth.py", line 46, in sign_up
user = User.query.filter_by(email=email).first()
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\orm\query.py", line 2760, in first
return self.limit(1)._iter().first()
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\orm\query.py", line 2844, in _iter
result = self.session.execute(
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\orm\session.py", line 1689, in execute
result = conn._execute_20(statement, params or {}, execution_options)
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\base.py", line 1582, in _execute_20
return meth(self, args_10style, kwargs_10style, execution_options)
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
return connection._execute_clauseelement(
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\base.py", line 1451, in _execute_clauseelement
ret = self._execute_context(
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\base.py", line 1813, in _execute_context
self._handle_dbapi_exception(
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\base.py", line 1994, in _handle_dbapi_exception
util.raise_(
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
raise exception
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
self.dialect.do_execute(
File "C:\Users\Lee Hyunjin\AppData\Local\Programs\Python\Python39\Lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
cursor.execute(statement, parameters)

**Comment by irllyneedhelp** [comment]
Have found the error, no need to be addressed.

I think I had made a typo when I initially made the database so the database had not been recording password. 

Deleting database.db and running main.py again solved it.
