### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_active'

### ISSUE THREAD

**Issue by TechStudent11** [techwithtim/Flask-Web-App-Tutorial#2]
Full traceback:

```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "W:\Flask-Web-App-Tutorial\website\auth.py", line 62, in sign_up
    login_user(user, remember=True)
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask_login\utils.py", line 166, in login_user
    if not force and not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
```

This happens when I try to sign up.
I have not modified any files.

**Comment by shree191007** [comment]
same issue

**Comment by IzziCooki** [comment]
same

**Comment by Gaurav-1411** [comment]
Same issue here. I was halfway through the course, when I created a user. So I could log in, but near the end, deleting notes wasn't working properly. So I decided to delete the database, as it automatically creates a new database if one doesn't already exist. But now I just can't sign up.

**Comment by TechStudent11** [comment]
Thanks for fixing this Tim!

**Comment by heewoonkim2020** [comment]
> 

You can just specify an existing table.
When it comes to Python you need the ability to understand errors.

**Comment by arjun0561** [comment]
You're the best at programming and coding! I can't thank you enough for so much you did to me.You literally changed my life! Thank you so much😀!

**Comment by xhuang23** [comment]
> I have still having issues. I am a bit over halfway through the video and I have not changed anything. The issue I am getting is as follows: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user [SQL: SELECT user.id AS user_id, user.email AS user_email, user.password AS user_password, user.first_name AS user_first_name FROM user WHERE user.email = ? LIMIT ? OFFSET ?] [parameters: ('[tim@gmail.com](mailto:tim@gmail.com)', 1, 0)] (Background on this error at: https://sqlalche.me/e/14/e3q8) Is there any way to fix this?

Try deleting your database.db file and re-run the code.

**Comment by millox3** [comment]
> Full traceback:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2464, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2450, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1867, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 39, in reraise
>     raise value
>   File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 39, in reraise
>     raise value
>   File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "W:\Flask-Web-App-Tutorial\website\auth.py", line 62, in sign_up
>     login_user(user, remember=True)
>   File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\flask_login\utils.py", line 166, in login_user
>     if not force and not user.is_active:
> AttributeError: 'NoneType' object has no attribute 'is_active'
> ```
> 
> This happens when I try to sign up. I have not modified any files.

check auth.py file in line 66 you will find it like this| return render_template("sign_up.html", user=current_user)  |change it to| return render_template("sign-up.html", user=current_user)

**Comment by maestro0101** [comment]
I have that issue can someone help me?

Traceback (most recent call last):
  File "E:\Pythoshka\Web-site\main.py", line 1, in <module>
    from website import create_app
  File "E:\Pythoshka\Web-site\website\__init__.py", line 5, in <module>
    from website import models
  File "E:\Pythoshka\Web-site\website\models.py", line 2, in <module>
    from . import db
ImportError: cannot import name 'db' from partially initialized module 'website'

**Comment by TechStudent11** [comment]
That is not the same error.

**Comment by RexshK** [comment]
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2095, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2080, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "c:\Users\shree\OneDrive\Desktop\PythonMINI\Projects\website\views.py", line 7, in home
return render_template("template/home.html")
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
ctx.app.jinja_env.get_or_select_template(template_name_or_list),
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
return self.get_template(template_name_or_list, parent, globals)
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
return self._load_template(name, globals)
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
template = self.loader.load(self, name, self.make_globals(globals))
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
source, filename, uptodate = self.get_source(environment, name)
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 59, in get_source
return self._get_source_fast(environment, template)
File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: template/home.html

**Comment by TechStudent11** [comment]
> File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2095, in **call** return self.wsgi_app(environ, start_response) File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2080, in wsgi_app response = self.handle_exception(e) File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app response = self.full_dispatch_request() File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request rv = self.handle_user_exception(e) File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request rv = self.dispatch_request() File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "c:\Users\shree\OneDrive\Desktop\PythonMINI\Projects\website\views.py", line 7, in home return render_template("template/home.html") File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template ctx.app.jinja_env.get_or_select_template(template_name_or_list), File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template return self.get_template(template_name_or_list, parent, globals) File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template return self._load_template(name, globals) File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template template = self.loader.load(self, name, self.make_globals(globals)) File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load source, filename, uptodate = self.get_source(environment, name) File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 59, in get_source return self._get_source_fast(environment, template) File "C:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 95, in _get_source_fast raise TemplateNotFound(template) jinja2.exceptions.TemplateNotFound: template/home.html

Not the same error. Please raise a new one.

**Comment by paulphysio** [comment]
Traceback (most recent call last):
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\django\c
ore\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\django\c
ore\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\django\v
iews\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra
mework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra
mework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra
mework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra
mework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra
mework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra
mework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\djoser\v
iews.py", line 136, in perform_create
    user = serializer.save()
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra
mework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\djoser\s
erializers.py", line 65, in create
    user = self.perform_create(validated_data)
  File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\djoser\s
erializers.py", line 75, in perform_create
    user.is_active = False
AttributeError: 'NoneType' object has no attribute 'is_active'

**Comment by TechStudent10** [comment]
> Traceback (most recent call last): File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\django\c ore\handlers\exception.py", line 55, in inner response = get_response(request) File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\django\c ore\handlers\base.py", line 197, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs) File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\django\v iews\decorators\csrf.py", line 54, in wrapped_view return view_func(*args, **kwargs) File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra mework\viewsets.py", line 125, in view return self.dispatch(request, *args, **kwargs) File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra mework\views.py", line 509, in dispatch response = self.handle_exception(exc) File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra mework\views.py", line 469, in handle_exception self.raise_uncaught_exception(exc) File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra mework\views.py", line 480, in raise_uncaught_exception raise exc File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra mework\views.py", line 506, in dispatch response = handler(request, *args, **kwargs) File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra mework\mixins.py", line 19, in create self.perform_create(serializer) File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\djoser\v iews.py", line 136, in perform_create user = serializer.save() File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\rest_fra mework\serializers.py", line 212, in save self.instance = self.create(validated_data) File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\djoser\s erializers.py", line 65, in create user = self.perform_create(validated_data) File "C:\Users\coder\Documents\auth_sys\backend\env\lib\site-packages\djoser\s erializers.py", line 75, in perform_create user.is_active = False AttributeError: 'NoneType' object has no attribute 'is_active'

Update your code base.

**Comment by hkemmerich** [comment]
Traceback (most recent call last):
  File "C:\Users\hugotk\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\hugotk\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\hugotk\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\hugotk\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\hugotk\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\hugotk\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\hugotk\Documents\ASK_Investimentos\WebApp\website\auth.py", line 54, in sign_up
    elif len(last_name) < 2:
**_TypeError: object of type 'NoneType' has no len()_**

**Comment by rizoxon** [comment]
in **auth.py** file change line 62 from _login_user(user, remember=True)_ to _login_user(new_user, remember=True)_   this will solve **AttributeError: 'NoneType' object has no attribute 'is_active'**  ERROR

**Comment by dijasoar** [comment]
> in **auth.py** file change line 62 from _login_user(user, remember=True)_ to _login_user(new_user, remember=True)_ this will solve **AttributeError: 'NoneType' object has no attribute 'is_active'** ERROR

it tells me that new_user is undefined, do i need to import new_user?
