### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by NnamOnye** [techwithtim/Flask-Web-App-Tutorial#23]
im having issues its says "**no module named 'flask_SQLAlchemy'**. " when I run the code,
 If anyone can offer assistance It would be greatly appreciated!

this is the full error message down below 

Traceback (most recent call last):
  File "/Users/michaelonyejekwe/PycharmProjects/Web Login/main.py", line 1, in <module>
    from website import create_app
  File "/Users/michaelonyejekwe/PycharmProjects/Web Login/website/__init__.py", line 2, in <module>
    from flask_SQLAlchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_SQLAlchemy'

**Comment by winbutlose** [comment]
On the command line you can try _pip list_ and make sure you see **Flask-SQLAlchemy**. If it's not there, it means the SQLAlchemy package we need to import isn't installed. Run _pip install Flask-SQLAlchemy_ to install it

**Comment by NnamOnye** [comment]
its already there but for some reason its not picking it up im using pycharm and I have SQLAlchemy  1.3.6
installed

**Comment by NnamOnye** [comment]
> On the command line you can try _pip list_ and make sure you see **Flask-SQLAlchemy**. If it's not there, it means the SQLAlchemy package we need to import isn't installed. Run _pip install Flask-SQLAlchemy_ to install it

its already there but for some reason its not picking it up im using pycharm and I have SQLAlchemy 1.3.6
installed
