### ISSUE TITLE
sqlalchemy.exc.OperationalError please help!

### ISSUE THREAD

**Issue by nicholas-guinther** [techwithtim/Flask-Web-App-Tutorial#4]
sqlalchemy.exc.OperationalError
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.first_name
[SQL: SELECT user.id AS user_id, user.email AS user_email, user.password AS user_password, user.first_name AS user_first_name 
FROM user 
WHERE user.email = ?
 LIMIT ? OFFSET ?]
[parameters: ('nick@gmail.com', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Traceback (most recent call last)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
cursor.execute(statement, parameters)

**Comment by nicholas-guinther** [comment]
This issue was solved by deleting the database and rerunning the app (which created a new database).
