### ISSUE TITLE
 jinja2.exceptions.TemplateNotFound: login.html

### ISSUE THREAD

**Issue by Darkydeliver** [techwithtim/Flask-Web-App-Tutorial#45]
jinja2.exceptions.TemplateNotFound
jinja2.exceptions.TemplateNotFound: login.html

Traceback (most recent call last)
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "C:\Users\Yuvan\Desktop\Programing\1. Project\website\auth.py", line 28, in login
return render_template("login.html", user=current_user)
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\templating.py", line 148, in render_template
ctx.app.jinja_env.get_or_select_template(template_name_or_list),
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
return self.get_template(template_name_or_list, parent, globals)
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\jinja2\environment.py", line 997, in get_template
return self._load_template(name, globals)
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\jinja2\environment.py", line 958, in _load_template
template = self.loader.load(self, name, self.make_globals(globals))
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\jinja2\loaders.py", line 125, in load
source, filename, uptodate = self.get_source(environment, name)
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\templating.py", line 59, in get_source
return self._get_source_fast(environment, template)
File "C:\Users\Yuvan\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\templating.py", line 95, in _get_source_fast
raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by ChrisReidyReply** [comment]
Had the same issue. 

in your __init__.py, in the "create_app" function definition you'll need to correct:
app = Flask(__name__)
to 
app = Flask(__name__,template_folder="template")

Link to the solution [source](https://sites.miis.edu/dreadkingrathalos/2020/05/20/solutions-of-jinja2-exceptions-templatenotfound-index-html/#:~:text=The%20error%20message%20was%20due,folder%20name%20it%20%E2%80%9CTemplates%E2%80%9D.)
