### ISSUE TITLE
NameError: func is not defined

### ISSUE THREAD

**Issue by CodinWithSkanda1** [techwithtim/Flask-Web-App-Tutorial#6]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    app = create_app()
  File "C:\Users\samud\OneDrive\Documents\Notes App\website\__init__.py", line 21, in create_app
    from .models import User, Note
  File "C:\Users\samud\OneDrive\Documents\Notes App\website\models.py", line 4, in <module>
    class Note(db.Model):
  File "C:\Users\samud\OneDrive\Documents\Notes App\website\models.py", line 7, in Note
    date = db.Column(db.DateTime(timezone=True), default=func.now())
NameError: name 'func' is not defined

**Comment by catter1** [comment]
Don't forget to import func.

`from sqlalchemy.sql import func`

**Comment by ShyhiemGilbert** [comment]
What about if the 'from sqlalchemy.sql import func' doesn't work? any common issues to look for
<img width="279" alt="Screenshot 2021-06-09 at 8 30 51 pm" src="https://user-images.githubusercontent.com/42538473/121417248-97c1c000-c961-11eb-81a8-8fcfba7d7688.png">
