### ISSUE TITLE
ImportError: cannot import name 'blueprint' from 'flask'

### ISSUE THREAD

**Issue by Golpavel** [techwithtim/Flask-Web-App-Tutorial#76]
Hi, I copied all the code form this tutorial, to make sure, but I always get this error, it supposed to be something with settings or instalation. 

Traceback (most recent call last):
  File "/Users/pavelgol/Coding/Flask web/main.py", line 3, in <module>
    app = create_app()
  File "/Users/pavelgol/Coding/Flask web/website/__init__.py", line 7, in create_app
    from .views import views
  File "/Users/pavelgol/Coding/Flask web/website/views.py", line 1, in <module>
    from flask import blueprint
ImportError: cannot import name 'blueprint' from 'flask' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/__init__.py)

Thank you.

**Comment by CODER6GC** [comment]
I had the same issue, but i changed my interpreter to python 3.10.2 and than it worked.

**Comment by Hammadnmt** [comment]
change the intepreter
