### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: home.html

### ISSUE THREAD

**Issue by Ainsleyem** [techwithtim/Flask-Web-App-Tutorial#78]
File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\Emens\OneDrive\python website\website\templates\views.py", line 9, in home
    return render_template("home.html")
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html
127.0.0.1 - - [27/Sep/2022 16:38:26] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [27/Sep/2022 16:38:26] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [27/Sep/2022 16:38:27] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [27/Sep/2022 16:38:28] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
 * Detected change in 'c:\\Users\\Emens\\OneDrive\\python website\\website\\templates\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 486-708-147
127.0.0.1 - - [27/Sep/2022 16:41:36] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\Emens\OneDrive\python website\website\templates\views.py", line 9, in home
    return render_template("home.html")
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html
127.0.0.1 - - [27/Sep/2022 16:41:37] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [27/Sep/2022 16:41:37] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [27/Sep/2022 16:41:38] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [27/Sep/2022 16:41:38] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
 * Detected change in 'c:\\Users\\Emens\\OneDrive\\python website\\website\\templates\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 486-708-147
 * Detected change in 'c:\\Users\\Emens\\OneDrive\\python website\\website\\templates\\__init__.py', reloading
 * Restarting with stat
C:\Users\Emens\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'c:\\Users\\Emens\\OneDrive\\python website\\app.py': [Errno 2] No such file or directory
PS C:\Users\Emens\OneDrive\python website> & C:/Users/Emens/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/Emens/OneDrive/python website/website/templates/__init__.py"
PS C:\Users\Emens\OneDrive\python website> & C:/Users/Emens/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/Emens/OneDrive/python website/app.py"
C:\Users\Emens\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'c:\\Users\\Emens\\OneDrive\\python website\\app.py': [Errno 2] No such file or directory
PS C:\Users\Emens\OneDrive\python website> & C:/Users/Emens/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/Emens/OneDrive/python website/website/templates/__init__.py"
PS C:\Users\Emens\OneDrive\python website> & C:/Users/Emens/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/Emens/OneDrive/python website/website/templates/__init__.py"
PS C:\Users\Emens\OneDrive\python website> & C:/Users/Emens/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/Emens/OneDrive/python website/main.py"
 * Serving Flask app 'website.templates'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 486-708-147
127.0.0.1 - - [27/Sep/2022 18:43:02] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [27/Sep/2022 18:43:02] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [27/Sep/2022 18:43:03] "GET /?__debugger__=yes&cmd=resource&f=more.png HTTP/1.1" 304 -
127.0.0.1 - - [27/Sep/2022 18:43:03] "GET /?__debugger__=yes&cmd=resource&f=less.png HTTP/1.1" 304 -
127.0.0.1 - - [27/Sep/2022 18:43:04] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [27/Sep/2022 18:43:12] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\Users\Emens\OneDrive\python website\website\templates\views.py", line 9, in home
    return render_template("home.html")
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\Emens\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html.

how do I fix this?

**Comment by NotAryanRamani** [comment]
What's the name of your folder in which the home.html file is located?

**Comment by Ainsleyem** [comment]
> What's the name of your folder in which the home.html file is located?
> 
> 

It is located in a "templates" folder

**Comment by mattmdjaga** [comment]
I had the same error and it happened because my folder was named "template" instead of "templates"
