### ISSUE TITLE
'Flask' object has no attribute 'login_manager'

### ISSUE THREAD

**Issue by Metior21** [techwithtim/Flask-Web-App-Tutorial#80]
Traceback (most recent call last):
  File "c:\Users\x\Desktop\Flask-Web-App-Tutorial-main\main.py", line 3, in <module>
    app = create_app()
  File "c:\Users\x\Desktop\Flask-Web-App-Tutorial-main\website\__init__.py", line 15, in create_app
    from .views import views
  File "c:\Users\x\Desktop\Flask-Web-App-Tutorial-main\website\views.py", line 2, in <module>
    from flask_login import login_required, current_user
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\__init__.py", line 12, in <module>
    from .login_manager import LoginManager
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\login_manager.py", line 33, in <module>
    from .utils import _create_identifier
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\utils.py", line 23, in <module>
    login_manager.init_app(app)
NameError: name 'login_manager' is not defined

I've tried following solution but it still gave the same error. 

https://stackoverflow.com/questions/31067249/attributeerror-flask-object-has-no-attribute-login-manager-login-manager

**Comment by ugrcnkaya** [comment]
same here? any solution?

**Comment by purvaa27** [comment]
ANY SOLUTIONS??/

**Comment by sylvan2501** [comment]
I think that under `db.init_app(app)` in the __init__.py file 
The following lines need to be added:
`login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)`
as well as a decorator function (I am not sure about it)
please refer to [https://www.digitalocean.com/community/tutorials/how-to-add-authentication-to-your-app-with-flask-login](url)
