### ISSUE TITLE
TypeError: create_all() got an unexpected keyword argument 'app'

### ISSUE THREAD

**Issue by nicknameyu** [techwithtim/Flask-Web-App-Tutorial#89]
just cloned the repo and run in debug mode and hit below error
```
Flask-Web-App-Tutorial % /usr/bin/python3 /projects/Flask-Web-App-Tutorial/main.py
Traceback (most recent call last):
  File "/projects/Flask-Web-App-Tutorial/main.py", line 3, in <module>
    app = create_app()
  File "/projects/Flask-Web-App-Tutorial/website/__init__.py", line 24, in create_app
    create_database(app)
  File "/projects/Flask-Web-App-Tutorial/website/__init__.py", line 39, in create_database
    db.create_all(app=app)
TypeError: create_all() got an unexpected keyword argument 'app'
```
Flask-Web-App-Tutorial % python3 --version
Python 3.9.6
What am I missing?

**Comment by tkburis** [comment]
See my pull request: https://github.com/techwithtim/Flask-Web-App-Tutorial/pull/90/commits/80de2dfef28b86a55fba224b364abd5311c01fc5

You need to wrap it in an app context for new versions of Flask SQLAlchemy.

**Comment by nicknameyu** [comment]
@tkburis , thanks, it works

**Comment by infinityGamer9** [comment]
thanks
